networks:
  default:
    name: gopher_ms_network

services:
  broker:
    build:
      context: ./broker_service
      dockerfile: broker-service.dev.Dockerfile
    restart: unless-stopped
    container_name: gopher_ms_broker
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./broker_service:/usr/src/app
    environment:
      - AIR_ENV=dev

  front_end:
    build:
      context: ./front_end
      dockerfile: front-end.Dockerfile
    restart: unless-stopped
    container_name: gopher_ms_front_end
    ports:
      - "80:80"
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./front_end:/usr/src/app
    environment:
      - AIR_ENV=dev
