networks:
  default:
    name: gopher_ms_network

services:
  broker:
    build:
      context: ./broker_service
      dockerfile: broker-service.Dockerfile
    restart: unless-stopped
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
